"service": "${self:custom.config.name}"
"useDotenv": true
"provider":
  "name": "aws"
  "runtime": "nodejs16.x"
  "memorySize": 1024
  "timeout": 10
  "iam":
    "role":
      "statements":
        - "Effect": "Allow"
          "Action": "*"
          "Resource": "arn:aws:qldb:*:*:*"
        - "Effect": "Allow"
          "Action":
            - "lambda:InvokeFunction"
          "Resource": "*"
  "environment":
    "stackName": "${self:custom.config.name}-${opt:stage, self:provider.stage, 'dev'}"
    "DO_TOKEN": "${env:DO_TOKEN}"
    "ALCHEMY_MUMBAI_KEY": "${env:ALCHEMY_MUMBAI_KEY}"
    "ALCHEMY_POLYGON_KEY": "${env:ALCHEMY_POLYGON_KEY}"
    "BASE_URL":
      "Fn::Join":
        - ""
        - - " https://"
          - "Ref": "ApiGatewayRestApi"
          - ".execute-api.${self:custom.region}.amazonaws.com/${self:custom.sta\
            ge}/"
    "ZAP_URL": "${env:ZAP_URL}"
    "internalKey": "${env:INTERNAL_KEY}"
    "COMPLETED_KEY": "${env:COMPLETE_KEY}"
    "ledgerName":
      "Ref": "QLDB"
  "layers":
    - "arn:aws:lambda:us-east-1:210049126456:layer:ssh2-lambda-layer:2"
"plugins":
  - "serverless-webpack"
  - "serverless-api-gateway-throttling"
  - "serverless-plugin-info-json"
  - "serverless-plugin-warmup"
  - "serverless-prune-plugin"
  - "serverless-dotenv-plugin"
"resources":
  "Description": "Interface for Quantum Ledger API"
  "Resources":
    "QLDB":
      "Type": "AWS::QLDB::Ledger"
      "Properties":
        "Name": "polynodesLedger"
        "PermissionsMode": "STANDARD"
        "DeletionProtection": "${self:custom.QLDB.deleteProtectionEnabled.${opt:stage,
          \"dev\"}, false}"
"custom":
  "config": "${file(./config.json)}"
  "apiGatewayThrottling":
    "maxRequestsPerSecond": 100
    "maxConcurrentRequests": 50
  "warmup":
    "prewarm": true
  "prune":
    "automatic": true
    "number": 1
  "webpack":
    "includeModules": false
  "stage": "${opt:stage, \"dev\"}"
  "region": "${opt:region, self:provider.region, \"us-east-1\"}"
  "QLDB":
    "deleteProtectionEnabled":
      "dev": false
      "prod": true
      "other": false
"functions":
  "listNodes":
    "handler": "handlers.listNodes"
    "events":
      - "http":
          "path": "/nodes"
          "method": "get"
          "cors": true
          "private": false
  "getNode":
    "handler": "handlers.getNode"
    "events":
      - "http":
          "path": "/nodes/{nodeId}"
          "method": "get"
          "cors": true
          "private": false
  "ip":
    "handler": "handlers.ip"
    "events":
      - "http":
          "path": "/nodes/{nodeId}/ip"
          "method": "get"
          "cors": true
          "private": false
  "ls":
    "handler": "handlers.ls"
    "events":
      - "http":
          "path": "/nodes/{nodeId}/ls"
          "method": "get"
          "cors": true
          "private": false
  "privateKey":
    "handler": "handlers.privateKey"
    "events":
      - "http":
          "path": "/nodes/{nodeId}/privateKey"
          "method": "get"
          "cors": true
          "private": false
  "build":
    "handler": "handlers.build"
    "events":
      - "http":
          "path": "/nodes"
          "method": "post"
          "cors": true
          "private": false
  "completedNode":
    "handler": "handlers.completedNode"
    "timeout": 25
    "events":
      - "http":
          "path": "/nodes/{nodeId}/completed"
          "method": "get"
          "cors": true
          "private": false
  "makeContract":
    "handler": "handlers.makeContract"
    "timeout": 300
  "deleteNode":
    "handler": "handlers.deleteNode"
    "events":
      - "http":
          "path": "/nodes/{nodeId}"
          "method": "delete"
          "cors": true
          "private": false
  "getJobs":
    "handler": "handlers.getJobs"
    "events":
      - "http":
          "path": "/nodes/{nodeId}/jobs"
          "method": "get"
          "cors": true
          "private": false
  "getJob":
    "handler": "handlers.getJob"
    "events":
      - "http":
          "path": "/nodes/{nodeId}/jobs/{jobId}"
          "method": "get"
          "cors": true
          "private": false
  "getJobRuns":
    "handler": "handlers.getJobRuns"
    "events":
      - "http":
          "path": "/nodes/{nodeId}/jobs/{jobId}/runs"
          "method": "get"
          "cors": true
          "private": false
  "getJobRun":
    "handler": "handlers.getJobRun"
    "events":
      - "http":
          "path": "/nodes/{nodeId}/jobs/{jobId}/runs/{runId}"
          "method": "get"
          "cors": true
          "private": false
  "createJob":
    "handler": "handlers.createJob"
    "timeout": 30
    "events":
      - "http":
          "path": "/nodes/{nodeId}/jobs"
          "method": "post"
          "cors": true
          "private": false
